# Integration test dummy file
# Generated at 2026-03-18T20:32:28.188253+00:00
# This simulates a code fix generated by Track 2

def fixed_upsert(pipeline_definition, role_arn):
    """Fixed version of Pipeline.upsert() that handles dict role_arn."""
    if isinstance(role_arn, dict):
        role_arn = role_arn.get("arn", role_arn.get("RoleArn", ""))
    return pipeline_definition, role_arn
